IF OBJECT_ID('PLAYER', 'U') IS NOT NULL
    DROP TABLE IF EXISTS PLAYER;
CREATE TABLE PLAYER
(
    ID       int not null identity primary key,
    USER_ID  int,
    NICKNAME varchar(50)
)

IF OBJECT_ID('ARENA', 'U') IS NOT NULL
    DROP TABLE IF EXISTS ARENA;
CREATE TABLE ARENA
(
    ID     int not null identity primary key,
    WEIGHT int,
    HEIGHT int
)

IF OBJECT_ID('ARENA_CELL', 'U') IS NOT NULL
    DROP TABLE IF EXISTS ARENA_CELL;
CREATE TABLE ARENA_CELL
(
    ARENA_ID   int,
    PLAYER_ID  int,
    IS_MINE    int default 0,
    POSITION_X int,
    POSITION_Y int
)

ALTER TABLE ARENA_CELL
    ADD FOREIGN KEY (ARENA_ID) REFERENCES ARENA (ID);
ALTER TABLE ARENA_CELL
    ADD FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (ID);


IF OBJECT_ID('GAME', 'U') IS NOT NULL
    DROP TABLE IF EXISTS GAME;
CREATE TABLE GAME
(
    ID            int not null identity primary key,
    ARENA_ID      int,
    WINNER        int,
    NEXT_MOVE     int,
    STARTING_DATE datetime,
    ENDING_DATE   datetime
)

ALTER TABLE GAME
    ADD FOREIGN KEY (ARENA_ID) REFERENCES ARENA (ID);
ALTER TABLE GAME
    ADD FOREIGN KEY (WINNER) REFERENCES PLAYER (ID);
ALTER TABLE GAME
    ADD FOREIGN KEY (NEXT_MOVE) REFERENCES PLAYER (ID);

IF OBJECT_ID('GAME_PLAYER', 'U') IS NOT NULL
    DROP TABLE IF EXISTS GAME_PLAYER;
CREATE TABLE GAME_PLAYER
(
    GAME_ID   int,
    PLAYER_ID int
)

ALTER TABLE GAME_PLAYER
    ADD FOREIGN KEY (GAME_ID) REFERENCES GAME (ID);
ALTER TABLE GAME_PLAYER
    ADD FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (ID);